plugins {
    id('groovy')
    id('java-gradle-plugin')
    id('idea')
    id('maven-publish')
    id('com.gradle.plugin-publish') version '2.1.1'
}

group = 'org.graceframework.plugins'

ext.isReleaseVersion = !version.endsWith('SNAPSHOT')
ext.pomInfo = {
    delegate.url 'https://github.com/grace-plugins/grace-asset-pipeline'

    delegate.licenses {
        delegate.license {
            delegate.name 'The Apache Software License, Version 2.0'
            delegate.url 'https://www.apache.org/licenses/LICENSE-2.0.txt'
            delegate.distribution 'repo'
        }
    }

    delegate.scm {
        delegate.url 'scm:git@github.com:grace-plugins/grace-asset-pipeline.git'
        delegate.connection 'scm:git@github.com:grace-plugins/grace-asset-pipeline.git'
        delegate.developerConnection 'scm:git@github.com:grace-plugins/grace-asset-pipeline.git'
    }

    delegate.developers {
        delegate.developer {
            delegate.id 'rainboyan'
            delegate.name 'Michael Yan'
            delegate.email 'rain@rainboyan.com'
        }
    }
}


repositories {
    // mavenLocal()
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
    withJavadocJar()
}

dependencies {
    api gradleApi()
    api localGroovy()

    api project(':asset-pipeline-core')
    api 'com.google.javascript:closure-compiler-unshaded:v20240317'
    testImplementation('org.spockframework:spock-core:2.4-groovy-4.0')
}

test {
    testLogging {
        exceptionFormat = 'full'
        showStandardStreams = true
    }
}

gradlePlugin {
    website = 'https://github.com/grace-plugins/grace-asset-pipeline'
    vcsUrl = 'https://github.com/grace-plugins/grace-asset-pipeline.git'

    plugins {
        assetPipeline {
            id = 'org.graceframework.asset-pipeline'
            displayName = 'Grace Asset Pipeline Gradle Plugin'
            description = 'Asset-Pipeline is a plugin used for managing and processing static assets in Grace applications primarily via Gradle.'
            tags.set(['grace-framework', 'assets', 'asset-pipeline'])
            implementationClass = 'asset.pipeline.gradle.AssetPipelinePlugin'
        }
    }
}

afterEvaluate {
    signing {
        required = isReleaseVersion && gradle.taskGraph.hasTask("publish")
        Publication[] publications = new Publication[publishing.publications.size()]
        publishing.publications.findAll().toArray(publications)
        sign(publications)
    }
}

project.afterEvaluate {
    project.publishing.publications.each { MavenPublication publication->
        publication.pom {
            if (publication.name == "maven" || publication.name == "pluginMaven") {
                name = "Grace Asset Pipeline Gradle Plugin"
                description = "Asset-Pipeline is a plugin used for managing and processing static assets in Grace applications primarily via Gradle."
            }

            if (publication.name == "pluginMaven" || publication.name.endsWith("PluginMarkerMaven")) {
                withXml {
                    def xml = asNode()
                    xml.children().last() + pomInfo
                }
            }
        }
    }
}