[[introduction]]
== Introduction

The asset-pipeline provides first class static and 'not so static' asset management for the JVM including many native framework integrations. It is highly extensible and provides processing of dynamic languages like LESS, SASS, Coffee, Typescript, and more. This goes beyond simple asset packaging and processing (making tools like grunt or webpack unnecessary for building high quality single page apps on the JVM), but also takes it a step further by providing features for optimally serving assets from your application as well.

This guide documents configuration and usage examples of the asset-pipeline plugin.

=== Overview

The Asset-Pipeline is a plugin used for managing and processing static assets in Grace applications primarily via Gradle. Asset-Pipeline functions include processing and minification of both CSS and JavaScript files.

**Features:**

* Asset Bundling
* Css Minification / Relative Path assertion
* Js Minification
* Js SourceMap Generation
* File Encoding Support
* GZIP File Generation
* Last-Modified Header
* Cache Digest Names (Creates cache digested names and stores aliases in a manifest.properties)

[IMPORTANT]
====
This repository is a fork of https://github.com/bertramdev/asset-pipeline[Asset-Pipeline], developed to support Grace only. 
Since Grails does not currently support Spring Boot 3.0+, this plugin does not support Grails 5/6.
====
