=== Getting Started

Getting started with Gradle is very quick and easy. The `asset-pipeline-gradle` plugin is included in both the Gradle plugin repository as well as Maven. For those of you not familiar with https://gradle.org[Gradle] it is a very powerful build tooling system that you should definitely check out.

IMPORTANT: Asset-Pipelines build classes are not directly dependent on Gradle and can be easily integrated into other build tooling frameworks like Maven.

In its simplest form the `build.gradle` file might look like this:

[source,groovy,subs="attributes"]
.build.gradle
----
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "org.graceframework.plugins:asset-pipeline-gradle:{version}"
    }
}

apply plugin: "org.graceframework.asset-pipeline"
----

Or even simpler:

[source,groovy,subs="attributes"]
.build.gradle
----
//Gradle 2.1+
plugins {
    id "org.graceframework.asset-pipeline" version "{version}"
}
----

When this plugin is added a couple tasks and extensions are automatically registered:

* `assetCompile` - Compiles and packages assets from `src/assets` into `build/assets`
* `assetPluginPackage` - Copies all assets unprocessed into an archive useful for plugin jars similar to webjars.
* `assetClean` - Cleans and resets the `build/assets` directory.

NOTE: All of these tasks support Gradle's incubating continuous build feature. Simply prefix the task with `-t`.

Create a folder `src/assets` and subfolders:

* `javascripts`
*  `stylesheets`
*  `html`
*  `images`
*  `...`

Now assets can be packaged and processed with ease and performance far outpacing other static asset build tooling.

