plugins {
    id 'groovy'
    id 'org.graceframework.grace-doc' version "$graceVersion"
}

def DOCUMENTATION_GROUP = 'Documentation'

ext['springBootVersion'] = '3.5.14'
ext['springFrameworkVersion'] = '6.2.18'

repositories {
    mavenCentral()
}

configurations {
    documentation
}

dependencies {
    documentation 'com.github.javaparser:javaparser-core:3.26.4'
    documentation "org.apache.groovy:groovy:$groovyVersion"
    documentation "org.apache.groovy:groovy-ant:$groovyVersion"
    documentation "org.graceframework:grace-web-url-mappings:$graceVersion"
    documentation "org.springframework:spring-web:$springFrameworkVersion"
    documentation "org.springframework.boot:spring-boot:$springBootVersion"
}

def cleanTask = project.tasks.findByName('clean')
if (cleanTask == null) {
    task clean(type: Delete) {
        delete(buildDir)
    }
}
else {
    cleanTask.doLast {
        ant.delete(dir: 'build/docs')
    }
}

tasks.withType(Groovydoc) {
    group = DOCUMENTATION_GROUP
    docTitle = "Grace Asset Pipeline - ${project.version}"
    destinationDir = project.file('build/docs/manual/api')
    def files = []
    project.rootProject.subprojects
            .findAll { !it.name != 'docs' && !it.name.startsWith('examples') }
            .each { subproject ->
                if(subproject.file('src/main/groovy').exists()) {
                    files += subproject.files('src/main/groovy')
                }
                if(subproject.file('src/main/java').exists()) {
                    files += subproject.files('src/main/java')
                }
            }
    if (project.file('src/main/groovy').exists()) {
        files += project.files('src/main/groovy')
    }
    source = files
    classpath += configurations.documentation
    link('https://docs.oracle.com/en/java/javase/17/docs/api/java.base/', 'java.', 'jakarta.')
    link("https://docs.groovy-lang.org/docs/groovy-${groovyVersion}/html/gapi/",  'groovy.', 'org.codehaus.groovy.', 'org.apache.groovy.')
    link('https://docs.spring.io/spring-boot/3.5/api/java',  'org.springframework.boot.')
    link("https://docs.spring.io/spring-framework/docs/${springFrameworkVersion}/javadoc-api",  'org.springframework.core.', 'org.springframework.context.', 'org.springframework.beans.')
    link("https://graceframework.org/grace-framework/${graceVersion}/api/", 'grails.web.', 'grails.web.mapping.', 'org.graceframework.')
}

tasks.register('docs') { task ->
    task.dependsOn groovydoc, publishGuide
}

def assembleTask = project.tasks.findByName('assemble')
if (assembleTask == null) {
    task assemble(dependsOn: docs, type:Zip) {
        baseName = "${project.name}-${project.version}"
        destinationDir = new File(project.buildDir, 'distributions')
        from project.files("${buildDir}/docs")
    }
}
